version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build completed.
      # Upload index.html directly to S3 root for static hosting
      - aws s3 cp index.html s3://oes-web-dashboard/index.html

artifacts:
  files:
    - '**/*'
  base-directory: .
  name: build-artifacts
