version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
      - aws --version
  build:
    commands:
      - echo "Uploading index.html and styles.css to oes-web-dashboard..."
      - |
        if [ -f index.html ]; then
          aws s3 cp index.html s3://oes-web-dashboard/index.html || echo "Failed to upload index.html"
        else
          echo "index.html not found"
        fi
      - |
        if [ -f styles.css ]; then
          aws s3 cp styles.css s3://oes-web-dashboard/styles.css || echo "Failed to upload styles.css"
        else
          echo "styles.css not found"
        fi

artifacts:
  files:
    - '**/*'
  base-directory: .
  name: build-artifact
